In [1]:
from datascience import *
import numpy as np

## Review

**Discussion Question 1:** Question 4, Midterm, Spring 2023.
- What will the following Python expression evaluate to?

In [ ]:
'data' + str(round(8.2))

**Discussion Question 1:** Question 1, Final, Fall 2019.
- What will the following Python expression evaluate to?

In [ ]:
make_array(1,2,3) * 2

____

In [3]:
nba = Table.read_table('nba_salaries.csv')

In [5]:
recent_curry = nba.where('name', 'Stephen Curry').where('season', are.above(2015))
recent_curry

rank | name          | position | team                  | salary   | season
61   | Stephen Curry | PG       | Golden State Warriors | 11370786 | 2016
82   | Stephen Curry | PG       | Golden State Warriors | 12112359 | 2017
1    | Stephen Curry | PG       | Golden State Warriors | 37457154 | 2018
1    | Stephen Curry | PG       | Golden State Warriors | 37457154 | 2019
1    | Stephen Curry | PG       | Golden State Warriors | 40231758 | 2020

**Discussion Question 3:** 
- Which of the following two lines of code correctly calculates the average salary of Steph Curry from 2016-2020?

In [ ]:
np.average(recent_curry.select('salary'))

In [ ]:
np.average(recent_curry.column('salary'))

____

In [4]:
recent_lebron = nba.where('name', 'LeBron James').where('season', are.above(2015))
recent_lebron

rank | name         | position | team                | salary   | season
2    | LeBron James | SF       | Cleveland Cavaliers | 22970500 | 2016
1    | LeBron James | SF       | Cleveland Cavaliers | 30963450 | 2017
3    | LeBron James | SF       | Los Angeles Lakers  | 35654150 | 2019
7    | LeBron James | SF       | Los Angeles Lakers  | 37436858 | 2020

**Discussion Question (Challenge)**:
- Which one of following calculations can be performed using array arithmetic and the tables `recent_curry` and `recent_lebron`?
    - The difference in the average salaries of LeBron James and Stephen Curry from 2016-2020
    - The average of the differences of salaries of Lebron James and Stephen Curry from 2016-2020

In [ ]:
np.average(recent_stephen_curry.column('salary'))

## Ranges

In [7]:
make_array(0,1,2,3,4,5,6)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
np.arange(stop=7)

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [16]:
np.arange(start=0, stop=7, step=1)

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [18]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [17]:
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

**Discussion Question 4:**    
- What will the following Python expression evaluate to?


In [23]:
make_array(1,2,3) + np.arange(start=1, stop=4)

array([2, 4, 6])

## Creating Tables

**Way 1:** Reading from a file

In [26]:
nba = Table.read_table('nba_salaries.csv')
nba.show(6)

**Way 2:** Creating from scratch

In [27]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [28]:
Table()

In [29]:
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste

In [30]:
southside.with_column('Blocks from campus', np.arange(4))

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [31]:
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

## Case Study: W.E.B. DuBois

In [48]:
du_bois = Table.read_table('du_bois.csv')

**Task**: Return the number of rows and columns in this dataset.

In [47]:
du_bois.num_rows

7

In [51]:
du_bois.num_columns

8

**Task:** Return the information that was recorded on each "individual" in this dataset.

In [53]:
du_bois.labels

('CLASS',
 'ACTUAL AVERAGE',
 'RENT',
 'FOOD',
 'CLOTHES',
 'TAXES',
 'OTHER',
 'STATUS')

In [52]:
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

**Task:** Isolate just the information about the families with the highest earning income bracket on average, circa 1900.

In [43]:
du_bois.sort('ACTUAL AVERAGE', descending=True)

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR

In [44]:
du_bois.sort('ACTUAL AVERAGE', descending=True).take(0)

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

**Task:** Estimate the amount of money each that each income class of Black Americans spent on food, circa 1900.

In [45]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

In [46]:
du_bois = du_bois.with_columns('Food $', food_dollars)
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25