In [25]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Review Questions

In [82]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

**Review Question 1**: How many rows and columns are in the `cones` table once the following cell has finished executing?

In [ ]:
cones.select('Flavor', 'Price')

**Review Question 2**: Which one of the following two lines of code fail?

In [ ]:
cones.drop('Color').where('Color', 'pink')

In [ ]:
nba.where('Color', 'pink').drop('Color')

## `int` and `float`

In [ ]:
1 + 3 

In [ ]:
1234567 * 890

In [ ]:
1234567 ** 20

____

In [ ]:
2024

In [ ]:
1012 * 2

In [ ]:
4048/2

_______

#### More on `float` values

In [1]:
10/3

3.3333333333333335

In [2]:
75892745.215489247589274985712

75892745.21548925

In [3]:
75892745.215489247589274985712 - 75892745.21548925

0.0

____

In [6]:
(13 ** 0.5) 

3.605551275463989

In [5]:
(13 ** 0.5) ** 2

12.999999999999998

____

In [7]:
(1234567 ** 20)/1

6.765396925633149e+121

#### Strings

In [ ]:
'Flavor'

In [ ]:
Flavor

In [ ]:
'I wouldn't ever ignore my homework'

In [ ]:
"I wouldn't ever ignore my homework"

________

In [10]:
"I" + "wouldn't ever ignore my homework"

"Iwouldn't ever ignore my homework"

In [11]:
"I" + " wouldn't ever ignore my homework"

"I wouldn't ever ignore my homework"

In [12]:
"Ben" + " 10"

'Ben 10'

In [13]:
"Ben" + 10

TypeError: can only concatenate str (not "int") to str

In [8]:
'ha' * 100

'hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha'

#### Conversions

In [17]:
int('3')

3

In [70]:
int(float('3.0'))

3

In [69]:
float(int('3'))

3.0

In [14]:
str(10)

'10'

In [16]:
'Ben ' + str(10)

'Ben 10'

#### "Conversions"

In [ ]:
float('one point two')

In [79]:
int(1.2)

1

In [76]:
int(1.23)

1

In [75]:
round(1.23, ndigits = 1)

1.2

In [77]:
int(1.6)

1

In [78]:
round(1.6)

2

In [72]:
2 + float(8)

10.0

_____

#### Every value has a **data type**

In [19]:
type(10)

int

In [20]:
a = 10

In [21]:
type(a)

int

In [29]:
type(1012*2)

int

In [30]:
type(4048/2)

float

In [22]:
type('Ben')

str

In [23]:
type('Ben ' + str(10))

str

In [27]:
type(abs)

builtin_function_or_method

In [26]:
nba = Table.read_table('nba_salaries.csv')
type(nba)

datascience.tables.Table

#### **Arrays** are sequences of values

In [35]:
my_array = make_array(1, 2, 3, 4)

In [36]:
my_array

array([1, 2, 3, 4])

In [64]:
type(my_array)

numpy.ndarray

In [51]:
my_array.item(1)

2

In [52]:
my_array.item(0)

1

In [53]:
my_array.item(4)

IndexError: index 4 is out of bounds for axis 0 with size 4

____

In [37]:
my_array + 2

array([3, 4, 5, 6])

In [38]:
my_array * 2

array([2, 4, 6, 8])

In [39]:
my_array ** 2

array([ 1,  4,  9, 16])

In [40]:
my_array_2 = make_array(4,5,6,7)

In [41]:
my_array + my_array_2

array([ 5,  7,  9, 11])

In [42]:
my_array + make_array(8,9,10)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [43]:
my_array * make_array(8,9,10)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

**Functions on arrays**

In [46]:
my_array = make_array(1, 2, 3, 4)

In [47]:
sum(my_array)

10

In [48]:
np.average(my_array)

2.5

In [49]:
len(my_array)

4

_____

In [54]:
nba.show(6)

In [56]:
nba.sort('season', descending=True).show(6)

In [59]:
nba.select('salary')

salary
17142000
16806000
15004000
15000000
14795000
14000000
11910000
11020000
10800000
10780000
... (9446 rows omitted)

In [60]:
type(nba.select('salary'))

datascience.tables.Table

In [61]:
nba.column('salary')

array([17142000, 16806000, 15004000, ...,   183115,   183115,   155647])

In [63]:
type(nba.column('salary'))

numpy.ndarray

In [62]:
np.average(nba.column('salary'))

4486115.181154822